spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sistemaDocumentacao
    username: root
    password: rot
    Driver: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
